export default {
  onMouseOver: 'mouseover.react',
  onMouseOut: 'mouseout.react',
  onMouseEnter: 'mouseenter.react',
  onMouseLeave: 'mouseleave.react',
  onMouseMove: 'mousemove.react',
  onMouseDown: 'mousedown.react',
  onMouseUp: 'mouseup.react',
  onMouseWheel: 'mousewheel.react',
  onClick: 'click.react',
  onDblClick: 'dblclick.react',
  onDragStar: 'dragstart.react',
  onDragEnd: 'dragend.react',
  onTouchStart: 'touchstart.react',
  onTouchMove: 'touchmove.react',
  onTouchEnd: 'touchend.react',
  onTap: 'tap.react',
  onDblTap: 'dbltap.react',
  onDragMove: 'dragmove.react',
  onContentClick:'contentClick.react',
  onContentMouseOver:'contentMouseover.react',
  onContentMouseMove:'contentMousemove.react',
  onContentMouseOut:'contentMouseout.react',
  onContentMouseDown:'contentMousedown.react',
  onContentMouseUp:'contentMouseup.react',
  onContentDblClick:'contentDblclick.react',
  onContentTouchStart:'contentTouchstart.react',
  onContentTouchMove:'contentTouchmove.react',
  onContentTouchEnd:'contentTouchend.react',
  onContentTap:'contentTap.react',
  onContentDblTap:'contentDblTap.react'
};
