export default {
  onMouseOver: 'mouseover.react',
  onMouseOut: 'mouseout.react',
  onMouseEnter: 'mouseenter.react',
  onMouseLeave: 'mouseleave.react',
  onMouseMove: 'mousemove.react',
  onMouseDown: 'mousedown.react',
  onMouseUp: 'mouseup.react',
  onMouseWheel: 'mousewheel.react',
  onClick: 'click.react',
  onDblClick: 'dblclick.react',
  onDragStar: 'dragstart.react',
  onDragEnd: 'dragend.react',
  onTouchStart: 'touchstart.react',
  onTouchMove: 'touchmove.react',
  onTouchEnd: 'touchend.react',
  onTap: 'tap.react',
  onDblTap: 'dbltap.react',
  onDragMove: 'dragmove.react',
	onContentClick:'contentClick.react',
	onContentMouseover:'contentMouseover.react',
	onContentMousemove:'contentMousemove.react',
	onContentMouseout:'contentMouseout.react',
	onContentMousedown:'contentMousedown.react',
	onContentMouseup:'contentMouseup.react',
	onContentDblclick:'contentDblclick.react',
	onContentTouchstart:'contentTouchstart.react',
	onContentTouchmove:'contentTouchmove.react',
	onContentTouchend:'contentTouchend.react',
	onContentTap:'contentTap.react',
	onContentDblTap:'contentDblTap.react'
};
